name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '*/10 0-2,15-23 * * *'
  workflow_dispatch:

permissions:
  contents: read

env:
  CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
  CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
  GAME_KEY: ${{ vars.GAME_KEY }}
  LEAGUE_ID: ${{ vars.LEAGUE_ID }}
  TEAM_ID: ${{ vars.TEAM_ID }}
  YAHOO_TOKEN: ${{ secrets.YAHOO_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set Timezone
      uses: szenius/set-timezone@v1.0
      with:
        timezoneLinux: "America/New_York"
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Make hockey.py executable
      run: chmod +x hockey.py
    - name: Create directory for token storage
      run: mkdir -p /home/runner/work/fantasy-hockey-bot/fantasy-hockey-bot/tokens/
    - name: Run Hockey Bot
      run: |
        ./hockey.py
